Add `createcachetable` command to Python Docker service (#6405)
In an attempt to eliminate an error we're seeing on launch:

```
django.db.utils.ProgrammingError: relation "cfgov_default_cache" does not exist
```